"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 20:01:43.214456
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brigades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brigades')),
    sa.UniqueConstraint('external_id', name=op.f('uq_brigades_external_id')),
    sa.UniqueConstraint('name', name=op.f('uq_brigades_name'))
    )
    op.create_table('fault_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fault_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_fault_codes_code')),
    sa.UniqueConstraint('external_id', name=op.f('uq_fault_codes_external_id'))
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_purpose'), ['purpose'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('external_id', name=op.f('uq_materials_external_id')),
    sa.UniqueConstraint('name', name=op.f('uq_materials_name'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('external_id', name=op.f('uq_sections_external_id')),
    sa.UniqueConstraint('name', name=op.f('uq_sections_name'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('master', 'worker', 'boss', 'admin', name='role', native_enum=False, length=12), nullable=False),
    sa.Column('specialty', sa.String(length=60), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Enum('day', 'night', name='shift', native_enum=False, length=8), nullable=True),
    sa.Column('on_shift', sa.Boolean(), nullable=False),
    sa.Column('pin_hash', sa.String(length=160), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], name=op.f('fk_employees_brigade_id_brigades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('external_id', name=op.f('uq_employees_external_id')),
    sa.UniqueConstraint('login', name=op.f('uq_employees_login')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_employees_telegram_chat_id'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_brigade_id'), ['brigade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_role'), ['role'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('inv_number', sa.String(length=32), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('criticality', sa.Enum('A', 'B', 'C', name='criticality', native_enum=False), nullable=False),
    sa.Column('qr_code', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_equipment_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('external_id', name=op.f('uq_equipment_external_id')),
    sa.UniqueConstraint('inv_number', name=op.f('uq_equipment_inv_number')),
    sa.UniqueConstraint('qr_code', name=op.f('uq_equipment_qr_code'))
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_section_id'), ['section_id'], unique=False)

    op.create_table('time_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_code_id', sa.Integer(), nullable=False),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fault_code_id'], ['fault_codes.id'], name=op.f('fk_time_norms_fault_code_id_fault_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_norms')),
    sa.UniqueConstraint('fault_code_id', name=op.f('uq_time_norms_fault_code_id'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('planned', 'unplanned', name='ordertype', native_enum=False, length=12), nullable=False),
    sa.Column('priority', sa.Enum('emergency', 'high', 'normal', 'planned', name='priority', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'QUEUED', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'PAUSED', 'DONE', 'AI_REVIEW', 'REWORK', 'CLOSED', 'CANCELLED', name='orderstatus', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('norm_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fault_code_id', sa.Integer(), nullable=True),
    sa.Column('works_done', sa.Text(), nullable=True),
    sa.Column('no_materials', sa.Boolean(), nullable=False),
    sa.Column('closing_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rework_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boss_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['employees.id'], name=op.f('fk_orders_assignee_id_employees')),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], name=op.f('fk_orders_brigade_id_brigades')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_orders_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['fault_code_id'], ['fault_codes.id'], name=op.f('fk_orders_fault_code_id_fault_codes')),
    sa.ForeignKeyConstraint(['master_id'], ['employees.id'], name=op.f('fk_orders_master_id_employees')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_orders_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_assignee_status', ['assignee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_master_id'), ['master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index('ix_orders_status_deadline', ['status', 'deadline_at'], unique=False)

    op.create_table('time_norm_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_norm_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_time_norm_materials_material_id_materials')),
    sa.ForeignKeyConstraint(['time_norm_id'], ['time_norms.id'], name=op.f('fk_time_norm_materials_time_norm_id_time_norms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_norm_materials'))
    )
    op.create_table('ai_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='assessmentstatus', native_enum=False, length=12), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('verdict', sa.Enum('accepted', 'accepted_with_remarks', 'rework', name='verdict', native_enum=False, length=24), nullable=True),
    sa.Column('score_0_100', sa.Integer(), nullable=True),
    sa.Column('score_1_5', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('needs_master_review', sa.Boolean(), nullable=False),
    sa.Column('explanation_worker', sa.Text(), nullable=True),
    sa.Column('explanation_master', sa.Text(), nullable=True),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('master_override_score', sa.Integer(), nullable=True),
    sa.Column('master_comment', sa.Text(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['employees.id'], name=op.f('fk_ai_assessments_master_id_employees')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_ai_assessments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_assessments'))
    )
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assessments_order_id'), ['order_id'], unique=False)

    op.create_table('material_writeoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_writeoffs_material_id_materials')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_material_writeoffs_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_writeoffs'))
    )
    with op.batch_alter_table('material_writeoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_writeoffs_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_writeoffs_order_id'), ['order_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_notifications_employee_id_employees')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_notifications_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_employee_id'), ['employee_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.Enum('ISSUED', 'QUEUED', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'PAUSED', 'DONE', 'AI_REVIEW', 'REWORK', 'CLOSED', 'CANCELLED', name='orderstatus', native_enum=False, length=16), nullable=True),
    sa.Column('to_status', sa.Enum('ISSUED', 'QUEUED', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'PAUSED', 'DONE', 'AI_REVIEW', 'REWORK', 'CLOSED', 'CANCELLED', name='orderstatus', native_enum=False, length=16), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_order_events_actor_id_employees')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('before', 'after', name='photokind', native_enum=False, length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('thumb_path', sa.String(length=255), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], name=op.f('fk_photos_author_id_employees')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_photos_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_phash'), ['phash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_phash'))
        batch_op.drop_index(batch_op.f('ix_photos_order_id'))

    op.drop_table('photos')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_events_created_at'))

    op.drop_table('order_events')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_employee_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('material_writeoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_writeoffs_order_id'))
        batch_op.drop_index(batch_op.f('ix_material_writeoffs_material_id'))

    op.drop_table('material_writeoffs')
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assessments_order_id'))

    op.drop_table('ai_assessments')
    op.drop_table('time_norm_materials')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status_deadline')
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_section_id'))
        batch_op.drop_index(batch_op.f('ix_orders_master_id'))
        batch_op.drop_index(batch_op.f('ix_orders_equipment_id'))
        batch_op.drop_index('ix_orders_assignee_status')

    op.drop_table('orders')
    op.drop_table('time_norms')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_section_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_role'))
        batch_op.drop_index(batch_op.f('ix_employees_brigade_id'))

    op.drop_table('employees')
    op.drop_table('sections')
    op.drop_table('materials')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    op.drop_table('fault_codes')
    op.drop_table('brigades')
    # ### end Alembic commands ###
